<!-- Friend Modal -->
<div
    class="modal fade"
    id="friendModal"
    tabindex="-1" role="dialog"
    aria-hidden="true"
>
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">About Friend</h1>
                <button type="button" class="btn" data-dismiss="modal" aria-label="Close">
                    <i class="ti-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="card friend-request">
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                    About Friend Lorem Ipsim Dolaris...
                </div>
            </div>
        </div>
    </div>
</div>
